version: '3.3'
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        restart: unless-stopped
        # network_mode: host
        volumes:
            - /docker/rpi/data/zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        ports:
            # Frontend port
            - 1111:8080
        environment:
            - TZ=Europe/Berlin
        env_file:
            - .env
        devices:
            # Make sure this matched your adapter location
            - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2484123-if00:/dev/ttyACM0

    zwavejs2mqtt:
        container_name: zwavejs2mqtt
        privileged: true
        image: zwavejs/zwavejs2mqtt:latest
        restart: unless-stopped
        network_mode: host
        stop_signal: SIGINT
        environment:
            - SESSION_SECRET=<mysupersecretkey>
            - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
            - TZ=Europa/Oslo
        volumes:
            - /docker/rpi/data/zwavejs2mqtt:/usr/src/app/store
            - /dev/serial/by-id/usb-0658_0200-if00:/dev/zwave
        ports:
            - "8091:8091" # port for web interface
            - "3000:3000" # port for Z-Wave JS websocket server
