version: '3.3'
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        restart: unless-stopped
        volumes:
            - /docker/rpi/data/zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 1111:8080
        environment:
            - TZ=Europe/Berlin
            - DEBUG=zigbee-herdsman*
        env_file:
            - .env
        devices:
            - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2484123-if00:/dev/ttyACM0
