version: '3.3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    restart: unless-stopped
    # network_mode: host
    volumes:
      - /docker/rpi/data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 1111:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2484123-if00:/dev/ttyACM0

  zwavejs2mqtt:
      container_name: zwavejs2mqtt
      privileged: true
      image: zwavejs/zwavejs2mqtt:latest
      restart: unless-stopped
      network_mode: host
      # tty: true
      stop_signal: SIGINT
      environment:
        - SESSION_SECRET=<mysupersecretkey>
        - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
        # Uncomment if you want log times and dates to match your timezone instead of UTC
        # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        - TZ=Europa/Oslo
      # devices:
        # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
        # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
        # - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
      volumes:
        - /docker/rpi/data/zwavejs2mqtt:/usr/src/app/store
        - /dev/serial/by-id/usb-0658_0200-if00:/dev/zwave
      ports:
        - "8091:8091" # port for web interface
        - "3000:3000" # port for Z-Wave JS websocket server