version: '3'

networks:
    rustdesk-net:
        external: false

services:
    hbbs:
        container_name: hbbs
        ports:
            - 21115:21115
            - 21116:21116
            - 21116:21116/udp
            - 21118:21118
        image: rustdesk/rustdesk-server:latest
        restart: unless-stopped
        command: hbbs -r srv.angry.fish:21117
        volumes:
            - /docker/rudtdesk/hbbs:/root
        networks:
            - rustdesk-net
        depends_on:
            - hbbr

    hbbr:
        container_name: hbbr
        ports:
            - 21117:21117
            - 21119:21119
        image: rustdesk/rustdesk-server:latest
        restart: unless-stopped
        command: hbbr
        volumes:
            - /docker/rudtdesk/hbbr:/root
        networks:
            - rustdesk-net
