# Concat 'homeassistant' and 'other' docker-compose files
version: '3.9'
services:
    portainer:
        container_name: portainer
        #image: portainer/portainer
        image: portainer/portainer-ce
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/docker/portainer/data:/data'
        ports:
            - '9000:9000'
        environment:
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
        restart: "no"